{
  "id": "lukes1973/first-one-of-titanic-ml-from-disaster",
  "id_no": 408853,
  "title": "FIRST ONE OF Titanic:ML From Disaster",
  "code_file": "first-one-of-titanic-ml-from-disaster.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "titanic"
  ]
}